apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:15
        env:
        - name: POSTGRES_DB
          value: postgres
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: password
        volumeMounts:
        - name: init-script
          mountPath: /docker-entrypoint-initdb.d
        - name: pg-data
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: init-script
        configMap:
          name: pg-init-script
      - name: pg-data
        hostPath:
          path: /data/postgres-0
          type: DirectoryOrCreate